# Credit Risk Resampling Techniques

In [33]:
import warnings
warnings.filterwarnings('ignore')

In [34]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV and Perform Basic Data Cleaning

In [35]:
columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [36]:
# Load the data
url = 'https://raw.githubusercontent.com/MonikaSData/Credit_Risk_Analysis/main/LoanStats_2019Q1.csv'
#df = pd.read_csv(url)
#file_path = Path('https://github.com/MonikaSData/Credit_Risk_Analysis/blob/main/LoanStats_2019Q1.csv')
df = pd.read_csv(url, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

loan_amnt  int_rate  ...  hardship_flag debt_settlement_flag
0    10500.0    0.1719  ...              N                    N
1    25000.0    0.2000  ...              N                    N
2    20000.0    0.2000  ...              N                    N
3    10000.0    0.1640  ...              N                    N
4    22000.0    0.1474  ...              N                    N

[5 rows x 86 columns]

In [37]:
# Print all the column and their data type as a dictionary
print(dict(df.dtypes))

{'loan_amnt': dtype('float64'), 'int_rate': dtype('float64'), 'installment': dtype('float64'), 'home_ownership': dtype('O'), 'annual_inc': dtype('float64'), 'verification_status': dtype('O'), 'issue_d': dtype('O'), 'loan_status': dtype('O'), 'pymnt_plan': dtype('O'), 'dti': dtype('float64'), 'delinq_2yrs': dtype('float64'), 'inq_last_6mths': dtype('float64'), 'open_acc': dtype('float64'), 'pub_rec': dtype('float64'), 'revol_bal': dtype('float64'), 'total_acc': dtype('float64'), 'initial_list_status': dtype('O'), 'out_prncp': dtype('float64'), 'out_prncp_inv': dtype('float64'), 'total_pymnt': dtype('float64'), 'total_pymnt_inv': dtype('float64'), 'total_rec_prncp': dtype('float64'), 'total_rec_int': dtype('float64'), 'total_rec_late_fee': dtype('float64'), 'recoveries': dtype('float64'), 'collection_recovery_fee': dtype('float64'), 'last_pymnt_amnt': dtype('float64'), 'next_pymnt_d': dtype('O'), 'collections_12_mths_ex_med': dtype('float64'), 'policy_code': dtype('float64'), 'applicatio

In [38]:
# Print only columns that are type object (string)
for column in df:
    if df.dtypes[column]==np.object:
        print(f'{column} : column type is - {df.dtypes[column]}')
    

home_ownership : column type is - object
verification_status : column type is - object
issue_d : column type is - object
loan_status : column type is - object
pymnt_plan : column type is - object
initial_list_status : column type is - object
next_pymnt_d : column type is - object
application_type : column type is - object
hardship_flag : column type is - object
debt_settlement_flag : column type is - object


# Split the Data into Training and Testing

In [39]:
# Create our features
X = pd.get_dummies(df, columns=["home_ownership", "verification_status", "issue_d", 
                                "pymnt_plan","initial_list_status","next_pymnt_d", "application_type", 
                                "hardship_flag", "debt_settlement_flag"]).drop("loan_status", axis=1)

# Create our target
y = df["loan_status"]

In [40]:
X.describe()

loan_amnt      int_rate  ...  hardship_flag_N  debt_settlement_flag_N
count  68817.000000  68817.000000  ...          68817.0                 68817.0
mean   16677.594562      0.127718  ...              1.0                     1.0
std    10277.348590      0.048130  ...              0.0                     0.0
min     1000.000000      0.060000  ...              1.0                     1.0
25%     9000.000000      0.088100  ...              1.0                     1.0
50%    15000.000000      0.118000  ...              1.0                     1.0
75%    24000.000000      0.155700  ...              1.0                     1.0
max    40000.000000      0.308400  ...              1.0                     1.0

[8 rows x 95 columns]

In [41]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)

# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [43]:
# Resample the training data with the RandomOversampler
from imblearn import over_sampling, under_sampling
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

Counter(y_resampled)

Counter({'high_risk': 51352, 'low_risk': 51352})

In [44]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
logReg_model = LogisticRegression(solver='lbfgs', random_state=1)
logReg_model.fit(X_resampled, y_resampled)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [45]:
# Predict outcomes for test data set
y_predictions = logReg_model.predict(X_test)
pd.DataFrame({"Prediction": y_predictions, "Actual": y_test})

# Calculated the balanced accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predictions)

0.6674803836094159

In [46]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predictions)
cm

array([[   56,    31],
       [ 5690, 11428]])

In [47]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.64      0.67      0.02      0.66      0.43        87
   low_risk       1.00      0.67      0.64      0.80      0.66      0.43     17118

avg / total       0.99      0.67      0.64      0.80      0.66      0.43     17205



### SMOTE Oversampling

In [48]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE

smote_transform = SMOTE(random_state=1)
X_resampled, y_resampled = smote_transform.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'high_risk': 51352, 'low_risk': 51352})

In [49]:
# Train the Logistic Regression model using the resampled data
logReg_model.fit(X_resampled, y_resampled)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [50]:
# Calculated the balanced accuracy score
y_predict_smote = logReg_model.predict(X_test)
accuracy_score(y_test, y_predict_smote)

0.6505666957279861

In [51]:
# Display the confusion matrix
cm_smote = confusion_matrix(y_test, y_predict_smote)
cm_smote

array([[   54,    33],
       [ 5979, 11139]])

In [52]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_predict_smote))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.62      0.65      0.02      0.64      0.40        87
   low_risk       1.00      0.65      0.62      0.79      0.64      0.41     17118

avg / total       0.99      0.65      0.62      0.78      0.64      0.41     17205



# Undersampling

In this section, you will test an undersampling algorithms to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [53]:
# Resample the data using the ClusterCentroids resampler
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'high_risk': 260, 'low_risk': 260})

In [54]:
# Train the Logistic Regression model using the resampled data
logReg_model.fit(X_resampled, y_resampled)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [55]:
# Calculated the balanced accuracy score
y_predict_cc = logReg_model.predict(X_test)
accuracy_score(y_test, y_predict_cc)

0.4143562917756466

In [56]:
# Display the confusion matrix
cm_cc = confusion_matrix(y_test, y_predict_cc)
cm_cc

array([[   55,    32],
       [10044,  7074]])

In [57]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_predict_cc))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.63      0.41      0.01      0.51      0.27        87
   low_risk       1.00      0.41      0.63      0.58      0.51      0.26     17118

avg / total       0.99      0.41      0.63      0.58      0.51      0.26     17205



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [58]:
# Resample the training data with SMOTEENN
# Warning: This is a large dataset, and this step may take some time to complete
from imblearn.combine import SMOTEENN

smote_enn = SMOTEENN(random_state=1)
X_resampled, y_resampled = smote_enn.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'high_risk': 51351, 'low_risk': 46389})

In [59]:
# Train the Logistic Regression model using the resampled data
logReg_model.fit(X_resampled, y_resampled)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [60]:
# Calculated the balanced accuracy score
y_predict_enn = logReg_model.predict(X_test)
accuracy_score(y_test, y_predict_enn)

0.5505376344086022

In [61]:
# Display the confusion matrix
cm_enn = confusion_matrix(y_test, y_predict_enn)
cm_enn

array([[  62,   25],
       [7708, 9410]])

In [62]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_predict_enn))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.01      0.71      0.55      0.02      0.63      0.40        87
   low_risk       1.00      0.55      0.71      0.71      0.63      0.39     17118

avg / total       0.99      0.55      0.71      0.71      0.63      0.39     17205

